services:
  mysql:
    image: mysql:9.7
    container_name: cc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: hello
      MYSQL_DATABASE: cc_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cc_backend
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cc_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
